version: 2 
jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Make html
          command: cd docs && make html
      - run:
          name: Link check
          command: cd docs && make linkcheck
workflows:
  version: 2
  build:
    jobs:
      - test
